title:            johannesw
tagline:          'DevOps, Continuous Delivery, Cloud, Microservices, Web, Docker, Node, and other cool things'
description:      'DevOps, Continuous Delivery, Cloud, Microservices, Web, Docker, Node, and other cool things'
url:              http://johannesw.net
baseurl:          /

author:
  name:           'Johannes Wettinger'
  url:            https://github.com/jojow

gems:
- 'jekyll-paginate'

permalink:        pretty
paginate:         3
paginate_path:    'page:num'

kramdown:
  input: GFM
  syntax_highlighter: rouge
